### ISSUE TITLE
Firmware Tool Bug?

### ISSUE THREAD

**Issue by CipherDK** [3DO-EU/Enclosure-Nozzle-Camera-V2#2]
The firmware tool ( 3DO_FW_TOOL_armv7a ) change the "Nozzle Camera V1"  to "usb-3DO_3DO_4K_USB_CAMERA_EU" the same name  as "Enclosure  Camera V2"
after udate, v4l only list one camera then both are plug in with the same name on a Raspberry pi 4 running mainsail/klipper.

It listed the right name in the tool before update.

Need some parameter in the tool to tell the difference between Enclosure and Nozzle camera or inside the code.

**Comment by thbl** [comment]
Firmware had been updated :)
