### ISSUE TITLE
Failed to update firmware

### ISSUE THREAD

**Issue by slapalot** [3DO-EU/Enclosure-Nozzle-Camera-V2#3]
Hi.
When trying to update my 3do nozzle cam i get the following message when using the update tool:

Stopping crowsnest service...
[sudo] password for *****:
Opening device: /dev/video10
3DO Camera init failed.
Restarting crowsnest service...
Failed to run the executable: 3DO_FW_TOOL_aarch64

In my crowsnest log, the nozzle cam is set to /dev/video9, so I dont understand why the tool is trying to open /dev/video10

[crowsnest.log (6).txt](https://github.com/user-attachments/files/16961127/crowsnest.log.6.txt)

**Comment by thbl** [comment]
please share what MCU you are running at what linux image

**Comment by slapalot** [comment]
![Screenshot_20240919_161149_Chrome](https://github.com/user-attachments/assets/ab24ab42-337b-4cd3-aede-639ab5200d96)

Is this enough info? I am kinda noob when it comes to linux 😅

The camera is connected directly to the host :)
The host is a Bigtreetech Pi v2.0

**Comment by thbl** [comment]
please check the new tool
