### ISSUE TITLE
FW Tool not running on RatOS

### ISSUE THREAD

**Issue by thbl** [3DO-EU/Enclosure-Nozzle-Camera-V2#4]
Make sure FW tool works for RatOS
```
Linux VC4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Running the executable: 3DO_FW_TOOL_aarch64
/dev/fd/63: line 56: ./3DO_FW_TOOL_aarch64: No such file or directory
Failed to run the executable: 3DO_FW_TOOL_aarch64
```

**Comment by randellhodges** [comment]
Same issue with a Pi4 running Raspbian bookworm

6.6.51+rpt-rpi-v8
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"

What I can see for me, is that while the kernel is 64 bit, the userland is 32 bit.

https://forums.raspberrypi.com/viewtopic.php?t=357800

**Comment by thbl** [comment]
should be fixed now
