### ISSUE TITLE
New firmware update shared library error 

### ISSUE THREAD

**Issue by slapalot** [3DO-EU/Enclosure-Nozzle-Camera-V2#5]
![Screenshot_20241004_165428_Termius](https://github.com/user-attachments/assets/e72f7c15-e42e-4ffb-a717-615a77fa52ef)
![Screenshot_20241004_165359_Chrome](https://github.com/user-attachments/assets/e6cef6cb-a7b6-4a96-923f-fc229be086dc)

Hi. I tried to update the new camera firmware via ssh on my btt pi2, and got the following error: 
Running the executable: 3DO_FW_TOOL_aarch64
./3DO_FW_TOOL_aarch64: error while loading shared libraries: libSPV4L2.so: cannot open shared object file: No such file or directory
Failed to run the executable: 3DO_FW_TOOL_aarch64

**Comment by thbl** [comment]
should be fixed now

**Comment by kv318** [comment]
I'm running into the same error on Bookworm / Pi 5

**Comment by mikulik86** [comment]
I'm also getting this error.

**Comment by astrolemonade** [comment]
Hey, it's not fixed! I am still getting this error!
